
import streamlit as st
import pandas as pd
import joblib

# Load trained model
model = joblib.load("airguard_random_forest.pkl")

# Page configuration
st.set_page_config(
    page_title="AirGuard - Indoor Air Quality Predictor",
    page_icon="🌬️",
    layout="centered"
)

# Title
st.title("🌬️ AirGuard")
st.subheader("Indoor Air Quality PPM Predictor")

st.write(
    "Enter indoor environmental and sensor measurements "
    "to estimate the air-quality PPM level using machine learning."
)

st.info(
    "⚠️ This prediction is for educational and decision-support purposes "
    "only. It does not replace professional air-quality testing."
)

# User inputs
st.header("Enter Sensor Readings")

temperature = st.number_input(
    "Temperature (°C)",
    min_value=-20.0,
    max_value=60.0,
    value=25.0
)

humidity = st.number_input(
    "Humidity (%)",
    min_value=0.0,
    max_value=100.0,
    value=50.0
)

pressure = st.number_input(
    "Pressure (hPa)",
    min_value=800.0,
    max_value=1100.0,
    value=1013.0
)

gas_resistance = st.number_input(
    "Gas Resistance (Ohms)",
    min_value=0,
    value=50000
)

pm25 = st.number_input(
    "PM2.5",
    min_value=0,
    value=10
)

tvoc = st.number_input(
    "TVOC (ppb)",
    min_value=0,
    value=10
)

eco2 = st.number_input(
    "eCO2 (ppm)",
    min_value=0,
    value=400
)

voc_index = st.number_input(
    "VOC Index",
    min_value=0,
    value=100
)

mq135 = st.number_input(
    "MQ135 Value",
    min_value=0,
    value=70
)

voltage = st.number_input(
    "Voltage",
    min_value=0.0,
    value=0.23,
    format="%.6f"
)

hour = st.slider(
    "Hour",
    min_value=0,
    max_value=23,
    value=12
)

minute = st.slider(
    "Minute",
    min_value=0,
    max_value=59,
    value=30
)

day = st.slider(
    "Day",
    min_value=1,
    max_value=31,
    value=15
)

# Prediction
if st.button("🔍 Predict PPM"):

    input_data = pd.DataFrame([[
        temperature,
        humidity,
        pressure,
        gas_resistance,
        pm25,
        tvoc,
        eco2,
        voc_index,
        mq135,
        voltage,
        hour,
        minute,
        day
    ]], columns=[
        "Temperature (C)",
        "Humidity (%)",
        "Pressure (hPa)",
        "Gas Resistance (Ohms)",
        "PM2.5",
        "TVOC (ppb)",
        "eCO2 (ppm)",
        "VOC Index",
        "MQ135 Value",
        "Voltage",
        "Hour",
        "Minute",
        "Day"
    ])

    prediction = model.predict(input_data)[0]

    st.success(f"🌬️ Predicted PPM: {prediction:.4f}")

    st.write(
        "The predicted value is an estimate generated by the "
        "AirGuard machine-learning model."
    )
